### PR TITLE
Build packages for ARM

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

I'm attempting to get it to build packages for ARM on both Linux and macOS.

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
The tests fail on ARM Linux.  Possibly that's because they're being run under an emulator.  For the moment I'm just removing that build.  It's much less important than ARM Mac.

**Comment by peastman** [comment]
This is ready for review.

**Review by RaulPPelaez — APPROVED** [review]
LGTM

**Pull request merged**
